### ISSUE TITLE
Error while building the development environment for Stucco using MacOS

### ISSUE THREAD

**Issue by kirtanadarabal** [stucco/dev-setup#10]
Trackback of error:

TASK [smola.java : Install Java packages] **************************************
failed: [stucco] (item=[u'java_packages']) => {"failed": true, "item": ["java_packages"], "msg": "No package matching 'java_packages' is available"}

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

Any ideas on how to fix this?

**Comment by jgoodall** [comment]
What version of vagrant and virtual box are you using? Make sure you have the latest one.

**Comment by kirtanadarabal** [comment]
I am using the latest versions of virtualbox and vagrant (VirtualBox 5.1.18 and Vagrant 1.9.2). I had to use Ansible 1.7.0 to fix the error but after downgrading to Ansible 1.7.0 I got the error: 

failed: [stucco] => {"changed": true, "cmd": ["./populate-schema-indexes.sh"], "delta": "0:00:02.594864", "end": "2017-03-18 00:14:47.576916", "item": "", "rc": 255, "start": "2017-03-18 00:14:44.982052"}

The full traceback of the error:

stderr: JarClassLoader: Warning: org/apache/commons/beanutils/BasicDynaBean.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/beanutils/BasicDynaClass.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/beanutils/BeanAccessLanguageException.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/beanutils/BeanUtils.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/beanutils/BeanUtilsBean$1.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/beanutils/BeanUtilsBean.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/beanutils/ConstructorUtils.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/beanutils/ContextClassLoaderLocal.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/beanutils/ConversionException.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/beanutils/ConvertUtils.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/beanutils/ConvertUtilsBean.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/beanutils/Converter.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/beanutils/ConvertingWrapDynaBean.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/beanutils/DynaBean.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/beanutils/DynaClass.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/beanutils/DynaProperty.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/beanutils/JDBCDynaClass.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/beanutils/LazyDynaBean.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/beanutils/LazyDynaClass.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/beanutils/LazyDynaMap.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/beanutils/MappedPropertyDescriptor.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/beanutils/MethodUtils$MethodDescriptor.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/beanutils/MethodUtils.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/beanutils/MutableDynaClass.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/beanutils/NestedNullException.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/beanutils/PropertyUtils.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/beanutils/PropertyUtilsBean.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/beanutils/ResultSetDynaClass.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/beanutils/ResultSetIterator.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/beanutils/RowSetDynaClass.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/beanutils/WrapDynaBean.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/beanutils/WrapDynaClass.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/beanutils/converters/AbstractArrayConverter.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/beanutils/converters/BigDecimalConverter.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/beanutils/converters/BigIntegerConverter.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/beanutils/converters/BooleanArrayConverter.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/beanutils/converters/BooleanConverter.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/beanutils/converters/ByteArrayConverter.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/beanutils/converters/ByteConverter.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/beanutils/converters/CharacterArrayConverter.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/beanutils/converters/CharacterConverter.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/beanutils/converters/ClassConverter.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/beanutils/converters/DoubleArrayConverter.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/beanutils/converters/DoubleConverter.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/beanutils/converters/FileConverter.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/beanutils/converters/FloatArrayConverter.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/beanutils/converters/FloatConverter.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/beanutils/converters/IntegerArrayConverter.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/beanutils/converters/IntegerConverter.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/beanutils/converters/LongArrayConverter.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/beanutils/converters/LongConverter.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/beanutils/converters/ShortArrayConverter.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/beanutils/converters/ShortConverter.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/beanutils/converters/SqlDateConverter.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/beanutils/converters/SqlTimeConverter.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/beanutils/converters/SqlTimestampConverter.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/beanutils/converters/StringArrayConverter.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/beanutils/converters/StringConverter.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/beanutils/converters/URLConverter.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/beanutils/locale/BaseLocaleConverter.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/beanutils/locale/LocaleBeanUtils$Descriptor.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/beanutils/locale/LocaleBeanUtils.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/beanutils/locale/LocaleBeanUtilsBean$1.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/beanutils/locale/LocaleBeanUtilsBean$Descriptor.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/beanutils/locale/LocaleBeanUtilsBean.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/beanutils/locale/LocaleConvertUtils.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/beanutils/locale/LocaleConvertUtilsBean.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/beanutils/locale/LocaleConverter.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/beanutils/locale/converters/BigDecimalLocaleConverter.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/beanutils/locale/converters/BigIntegerLocaleConverter.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/beanutils/locale/converters/ByteLocaleConverter.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/beanutils/locale/converters/DateLocaleConverter.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/beanutils/locale/converters/DecimalLocaleConverter.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/beanutils/locale/converters/DoubleLocaleConverter.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/beanutils/locale/converters/FloatLocaleConverter.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/beanutils/locale/converters/IntegerLocaleConverter.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/beanutils/locale/converters/LongLocaleConverter.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/beanutils/locale/converters/ShortLocaleConverter.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/beanutils/locale/converters/SqlDateLocaleConverter.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/beanutils/locale/converters/SqlTimeLocaleConverter.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/beanutils/locale/converters/SqlTimestampLocaleConverter.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/beanutils/locale/converters/StringLocaleConverter.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/collections/ArrayStack.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/collections/Buffer.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/collections/BufferUnderflowException.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/collections/FastHashMap$1.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/collections/FastHashMap$CollectionView$CollectionViewIterator.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/collections/FastHashMap$CollectionView.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/collections/FastHashMap$EntrySet.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/collections/FastHashMap$KeySet.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/collections/FastHashMap$Values.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/collections/FastHashMap.class in lib/commons-beanutils-core-1.8.0.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/collections/ArrayStack.class in lib/commons-collections-3.2.1.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/collections/BufferUnderflowException.class in lib/commons-collections-3.2.1.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/collections/FastHashMap$1.class in lib/commons-collections-3.2.1.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/collections/FastHashMap$CollectionView$CollectionViewIterator.class in lib/commons-collections-3.2.1.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/collections/FastHashMap$CollectionView.class in lib/commons-collections-3.2.1.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/collections/FastHashMap$EntrySet.class in lib/commons-collections-3.2.1.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/collections/FastHashMap$KeySet.class in lib/commons-collections-3.2.1.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/collections/FastHashMap$Values.class in lib/commons-collections-3.2.1.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
JarClassLoader: Warning: org/apache/commons/collections/FastHashMap.class in lib/commons-collections-3.2.1.jar is hidden by lib/commons-beanutils-1.7.0.jar (with different bytecode)
Indexing failed
java.lang.NullPointerException: Missing environment variable STUCCO_DB_TYPE
	at gov.pnnl.stucco.schema.IndexDefinitionsToDB.main(IndexDefinitionsToDB.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.simontuffs.onejar.Boot.run(Boot.java:340)
	at com.simontuffs.onejar.Boot.main(Boot.java:166)
stdout: executing schema load and indexing...

FATAL: all hosts have already failed -- aborting

stucco                     : ok=50   changed=16   unreachable=0    failed=1   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

**Comment by MariaVincent** [comment]
Try to build feature/bulkLoad branch of dev-setup. This is the latest and the most stable version.

**Comment by mikeiannacone** [comment]
This problem shouldn't occur in current master (or hotfix) branches, closing issue.
