### ISSUE TITLE
Can't access 10.10.10.110:8000

### ISSUE THREAD

**Issue by TheGodOfObelisk** [stucco/dev-setup#15]
After I entered "vagrant up", results are listed below.

Bringing machine 'default' up with 'virtualbox' provider...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed version of
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you see
    default: shared folder errors, please make sure the guest additions within the
    default: virtual machine match the version of VirtualBox you have installed on
    default: your host and reload your VM.
    default: 
    default: Guest Additions Version: 5.0.12
    default: VirtualBox Version: 5.1
==> default: Setting hostname...
==> default: Configuring and enabling network interfaces...
==> default: Mounting shared folders...
    default: /vagrant => /home/lw/stucco
    default: /stucco-shared => /home/lw
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> default: flag to force provisioning. Provisioners marked to run always will still run.

But I cannot access 10.10.10.110:8000, why?
    Thank you very much!

**Comment by TheGodOfObelisk** [comment]
The OS I used is Ubuntu 16.04 and it runs as a native OS. Should I run it in a virtual machine?

**Comment by TheGodOfObelisk** [comment]
It works well eventually, thank you!

**Comment by shenfna** [comment]
> It works well eventually, thank you!

老哥怎么解决的呀？

**Comment by TheGodOfObelisk** [comment]
> > It works well eventually, thank you!
> 
> 老哥怎么解决的呀？

后面再运行vrgrant provision

**Comment by shenfna** [comment]
> > > It works well eventually, thank you!
> > 
> > 
> > 老哥怎么解决的呀？
> 
> 后面再运行vrgrant provision

请问一下，出现的ansible的错误，有什么解决的办法么，非常感谢。

**Comment by TheGodOfObelisk** [comment]
> > > > It works well eventually, thank you!
> > > 
> > > 
> > > 老哥怎么解决的呀？
> > 
> > 
> > 后面再运行vrgrant provision
> 
> 请问一下，出现的ansible的错误，有什么解决的办法么，非常感谢。

没什么印象了，截个图看看？ 其实他的dev版本配置出来啥都没有。

**Comment by shenfna** [comment]
> > > > > It works well eventually, thank you!
> > > > 
> > > > 
> > > > 老哥怎么解决的呀？
> > > 
> > > 
> > > 后面再运行vrgrant provision
> > 
> > 
> > 请问一下，出现的ansible的错误，有什么解决的办法么，非常感谢。
> 
> 没什么印象了，截个图看看？ 其实他的dev版本配置出来啥都没有。

TASK [smola.java : Install Java packages] **************************************
[DEPRECATION WARNING]: Invoking "apt" only once while using a loop via 
squash_actions is deprecated. Instead of using a loop to supply multiple items 
and specifying `pkg: "{{ item }}"`, please use `pkg: '{{ java_packages }}'` and
 remove the loop. This feature will be removed in version 2.11. Deprecation 
warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
failed: [stucco] (item=[u'oracle-java8-installer', u'oracle-java8-set-default']) => {"ansible_loop_var": "item", "changed": false, "item": ["oracle-java8-installer", "oracle-java8-set-default"], "msg": "No package matching 'oracle-java8-installer' is available"}

PLAY RECAP *********************************************************************
stucco                     : ok=11   changed=0    unreachable=0    failed=1    skipped=4    rescued=0    ignored=0   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

最后的信息是这样的。麻烦了因为我是第一次接触这个虚拟机。

**Comment by TheGodOfObelisk** [comment]
> > > > > > It works well eventually, thank you!
> > > > > 
> > > > > 
> > > > > 老哥怎么解决的呀？
> > > > 
> > > > 
> > > > 后面再运行vrgrant provision
> > > 
> > > 
> > > 请问一下，出现的ansible的错误，有什么解决的办法么，非常感谢。
> > 
> > 
> > 没什么印象了，截个图看看？ 其实他的dev版本配置出来啥都没有。
> 
> TASK [smola.java : Install Java packages] **************************************
> [DEPRECATION WARNING]: Invoking "apt" only once while using a loop via
> squash_actions is deprecated. Instead of using a loop to supply multiple items
> and specifying `pkg: "{{ item }}"`, please use `pkg: '{{ java_packages }}'` and
> remove the loop. This feature will be removed in version 2.11. Deprecation
> warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
> failed: [stucco] (item=[u'oracle-java8-installer', u'oracle-java8-set-default']) => {"ansible_loop_var": "item", "changed": false, "item": ["oracle-java8-installer", "oracle-java8-set-default"], "msg": "No package matching 'oracle-java8-installer' is available"}
> 
> PLAY RECAP *********************************************************************
> stucco : ok=11 changed=0 unreachable=0 failed=1 skipped=4 rescued=0 ignored=0
> 
> Ansible failed to complete successfully. Any error output should be
> visible above. Please fix these errors and try again.
> 
> 最后的信息是这样的。麻烦了因为我是第一次接触这个虚拟机。

你是在虚拟机里配置的这个吗？我当时用的原生Ubuntu，没有出现这个问题。当时有同学一起配置的，他们在虚拟机里配置这个虚拟机，出现了很多和你这个类似的错误，最后都没有解决。

**Comment by shenfna** [comment]
> > > > > > > It works well eventually, thank you!
> > > > > > 
> > > > > > 
> > > > > > 老哥怎么解决的呀？
> > > > > 
> > > > > 
> > > > > 后面再运行vrgrant provision
> > > > 
> > > > 
> > > > 请问一下，出现的ansible的错误，有什么解决的办法么，非常感谢。
> > > 
> > > 
> > > 没什么印象了，截个图看看？ 其实他的dev版本配置出来啥都没有。
> > 
> > 
> > TASK [smola.java : Install Java packages] **************************************
> > [DEPRECATION WARNING]: Invoking "apt" only once while using a loop via
> > squash_actions is deprecated. Instead of using a loop to supply multiple items
> > and specifying `pkg: "{{ item }}"`, please use `pkg: '{{ java_packages }}'` and
> > remove the loop. This feature will be removed in version 2.11. Deprecation
> > warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
> > failed: [stucco] (item=[u'oracle-java8-installer', u'oracle-java8-set-default']) => {"ansible_loop_var": "item", "changed": false, "item": ["oracle-java8-installer", "oracle-java8-set-default"], "msg": "No package matching 'oracle-java8-installer' is available"}
> > PLAY RECAP *********************************************************************
> > stucco : ok=11 changed=0 unreachable=0 failed=1 skipped=4 rescued=0 ignored=0
> > Ansible failed to complete successfully. Any error output should be
> > visible above. Please fix these errors and try again.
> > 最后的信息是这样的。麻烦了因为我是第一次接触这个虚拟机。
> 
> 你是在虚拟机里配置的这个吗？我当时用的原生Ubuntu，没有出现这个问题。当时有同学一起配置的，他们在虚拟机里配置这个虚拟机，出现了很多和你这个类似的错误，最后都没有解决。

我用的是原生centos 7 , ansible版本是2.8.4，vagrant版本是2.2.5, 安装完了之后直接运行的，还需要修改其他的配置么？

**Comment by TheGodOfObelisk** [comment]
> > > > > > > > It works well eventually, thank you!
> > > > > > > 
> > > > > > > 
> > > > > > > 老哥怎么解决的呀？
> > > > > > 
> > > > > > 
> > > > > > 后面再运行vrgrant provision
> > > > > 
> > > > > 
> > > > > 请问一下，出现的ansible的错误，有什么解决的办法么，非常感谢。
> > > > 
> > > > 
> > > > 没什么印象了，截个图看看？ 其实他的dev版本配置出来啥都没有。
> > > 
> > > 
> > > TASK [smola.java : Install Java packages] **************************************
> > > [DEPRECATION WARNING]: Invoking "apt" only once while using a loop via
> > > squash_actions is deprecated. Instead of using a loop to supply multiple items
> > > and specifying `pkg: "{{ item }}"`, please use `pkg: '{{ java_packages }}'` and
> > > remove the loop. This feature will be removed in version 2.11. Deprecation
> > > warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
> > > failed: [stucco] (item=[u'oracle-java8-installer', u'oracle-java8-set-default']) => {"ansible_loop_var": "item", "changed": false, "item": ["oracle-java8-installer", "oracle-java8-set-default"], "msg": "No package matching 'oracle-java8-installer' is available"}
> > > PLAY RECAP *********************************************************************
> > > stucco : ok=11 changed=0 unreachable=0 failed=1 skipped=4 rescued=0 ignored=0
> > > Ansible failed to complete successfully. Any error output should be
> > > visible above. Please fix these errors and try again.
> > > 最后的信息是这样的。麻烦了因为我是第一次接触这个虚拟机。
> > 
> > 
> > 你是在虚拟机里配置的这个吗？我当时用的原生Ubuntu，没有出现这个问题。当时有同学一起配置的，他们在虚拟机里配置这个虚拟机，出现了很多和你这个类似的错误，最后都没有解决。
> 
> 我用的是原生centos 7 , ansible版本是2.8.4，vagrant版本是2.2.5, 安装完了之后直接运行的，还需要修改其他的配置么？

抱歉我实在是记不清了，我就是跟着GitHub上的指导来的。印象中没有什么特别需要注意的地方。

**Comment by shenfna** [comment]
> > > > > > > > > It works well eventually, thank you!
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 老哥怎么解决的呀？
> > > > > > > 
> > > > > > > 
> > > > > > > 后面再运行vrgrant provision
> > > > > > 
> > > > > > 
> > > > > > 请问一下，出现的ansible的错误，有什么解决的办法么，非常感谢。
> > > > > 
> > > > > 
> > > > > 没什么印象了，截个图看看？ 其实他的dev版本配置出来啥都没有。
> > > > 
> > > > 
> > > > TASK [smola.java : Install Java packages] **************************************
> > > > [DEPRECATION WARNING]: Invoking "apt" only once while using a loop via
> > > > squash_actions is deprecated. Instead of using a loop to supply multiple items
> > > > and specifying `pkg: "{{ item }}"`, please use `pkg: '{{ java_packages }}'` and
> > > > remove the loop. This feature will be removed in version 2.11. Deprecation
> > > > warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
> > > > failed: [stucco] (item=[u'oracle-java8-installer', u'oracle-java8-set-default']) => {"ansible_loop_var": "item", "changed": false, "item": ["oracle-java8-installer", "oracle-java8-set-default"], "msg": "No package matching 'oracle-java8-installer' is available"}
> > > > PLAY RECAP *********************************************************************
> > > > stucco : ok=11 changed=0 unreachable=0 failed=1 skipped=4 rescued=0 ignored=0
> > > > Ansible failed to complete successfully. Any error output should be
> > > > visible above. Please fix these errors and try again.
> > > > 最后的信息是这样的。麻烦了因为我是第一次接触这个虚拟机。
> > > 
> > > 
> > > 你是在虚拟机里配置的这个吗？我当时用的原生Ubuntu，没有出现这个问题。当时有同学一起配置的，他们在虚拟机里配置这个虚拟机，出现了很多和你这个类似的错误，最后都没有解决。
> > 
> > 
> > 我用的是原生centos 7 , ansible版本是2.8.4，vagrant版本是2.2.5, 安装完了之后直接运行的，还需要修改其他的配置么？
> 
> 抱歉我实在是记不清了，我就是跟着GitHub上的指导来的。印象中没有什么特别需要注意的地方。

好的吧还是非常感谢。
