### ISSUE TITLE
Minimum real hardware requirements for STUCCO vagrant demo on OS-X?

### ISSUE THREAD

**Issue by gerth** [stucco/dev-setup#7]
Installing VB, Vagrant, (brew) and Ansible on a MacMini running Yosemite went fine.

However, "vagrant up" totally locked up the machine (totally meaning one has to hold the power button).
It had gotten as far as the step which was checking to make sure titan was running.

After a second lock-up, I did RTFM by scrolling down further and saw that the default VM provisioning expected a 10G machine with 4 CPUs whereas the Mini is (an admittedly old) 4G core 2 duo.
I tried modifying the vm.provider parameters to reflect reality (and even a bit more at 6G), but then the VM won't even finish booting and has to be brought down with "vagrant halt" force.

What are the minimum real hardware requirements?

**Comment by jgoodall** [comment]
Good question. Can you do a pull and try setting the `cores` to 2 and `memory` to 8gb in [the vagrantfile](https://github.com/stucco/dev-setup/blob/master/Vagrantfile#L7-L10) at the top and see if it finishes?

You can also try to reduce `--cpuexecutioncap` for Virtualbox:
https://github.com/stucco/dev-setup/blob/master/Vagrantfile#L59

**Comment by gerth** [comment]
I tried several variants of memory/cores in the OS-X Vagrantfile file, but since the first lock-up, the
boot never gets to point of starting the network (although it does start so the hardware virtualization is working).

This morning I'm guessing something needs to be blown away (.vagrant.d ?) so it can start over.
However, is there much point in continuing at all on a MacMini with only 4G of RAM? In my experience
it's seldom worthwhile to try and run a VM defined with substantially more h/w than is really there.

**Comment by jgoodall** [comment]
To clean out your vagrant environment in `dev-setup`, do:

    vagrant destroy -f && rm -rf ./.vagrant

Do you have access to a beefier machine? I am trying to build a demo environment with data loaded already, which would hugely reduce the cpu/memory requirements.

**Comment by gerth** [comment]
The beefier machines all run Linux which is why I moved in that direction.

My personal MBP is much beefier than the other Macs I have lying around so
that might make a good place to try the preloaded demo.

**Comment by gerth** [comment]
Moved to Linux....closing
